name: app_for_test
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  
  # Network
  dio: ^4.0.6
  # connectivity_plus: ^2.3.0
  http: 
  # responsive
  flutter_screenutil: ^5.5.3+2
  # state management 
  flutter_bloc: ^8.1.1
  # Cache & Storage
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Others
  easy_localization: ^3.0.0
  flutter_svg: ^1.1.1
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  intl: 
  lottie:
  # weather_icons: 3.0.0-nullsafety.x


  
  
  






dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/languages/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 700
      
      

